version: "3.9"

services:
  node:
    # image: node:22
    build: .
    init: true
    volumes:
      - ..:/workspace
    command: sleep infinity
    ports:
      - "3000:3000"
    environment:
      CONVEX_TMPDIR: /workspace/.convex
